# Generated by Django 4.2.27 on 2026-01-10 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc_dashboard', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='compliance_percentage',
            field=models.IntegerField(default=0, help_text='Compliance percentage (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Compliance %'),
        ),
        migrations.AddField(
            model_name='risk',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Compliance evidence file', null=True, upload_to='compliance_evidence/', verbose_name='Evidence File'),
        ),
        migrations.AddField(
            model_name='risk',
            name='evidence_uploaded',
            field=models.BooleanField(default=False, help_text='Has compliance evidence been uploaded?', verbose_name='Evidence Uploaded'),
        ),
        migrations.AddField(
            model_name='risk',
            name='last_evidence_update',
            field=models.DateTimeField(blank=True, help_text='Last time evidence was updated', null=True, verbose_name='Last Evidence Update'),
        ),
    ]
